name: Docker Pipeline

on:
  push:
    branches:
      - feature/docker-setup
  pull_request:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build Docker image
        run: docker build -t 4kuro/Postmodern-technologies:latest .
      
      - name: Push Docker image to Docker Hub
        run: docker push 4kuro/Postmodern-technologies:latest

  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Pull Docker image
        run: docker pull 4kuro/Postmodern-technologies:latest
      
      - name: Run tests
        run: docker run 4kuro/Postmodern-technologies:latest python -m unittest discover -s tests
